# Generated by Django 5.2.1 on 2025-07-15 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_service_alter_project_slug_alter_project_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='extra_features',
            field=models.TextField(blank=True, default=''),
        ),
    ]
