# Generated by Django 5.2.1 on 2025-07-15 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_service_extra_features_alter_service_features'),
    ]

    operations = [
    ]
