# Generated by Django 5.2.1 on 2025-07-15 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20250714_2336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='extra_features',
        ),
    ]
