# Generated by Django 5.2.1 on 2025-07-15 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_service_extra_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='features',
            field=models.TextField(blank=True),
        ),
    ]
